# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - cityinfoapi9

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_0424ab017aad48199b1f9f2308a7bcc7 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0e2ab4cceabc4d638131824b122df2ab }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0424ab017aad48199b1f9f2308a7bcc7 }}/raedaskware/cityinfoapi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'cityinfoapi9'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9e4be65aadc44cbc97f3413e9dc79afa }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_0424ab017aad48199b1f9f2308a7bcc7 }}/raedaskware/cityinfoapi:${{ github.sha }}'